use_frameworks!

platform :ios, '9.0'

target 'MeituDemo_Example' do
  pod 'MeituDemo', :path => '../'

  target 'MeituDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
